apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sleep-harmonizer.fullname" . }}
  labels:
    {{- include "sleep-harmonizer.labels" . | nindent 4 }}
data:
  SH_ADAPTER_MODE: {{ .Values.env.adapterMode | quote }}
  SH_API_VERSION: "v1"
