{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sleep-harmonizer.fullname" . }}
  labels:
    {{- include "sleep-harmonizer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  SH_DATABASE_URL: {{ printf "postgresql+asyncpg://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Values.postgresql.auth.database | b64enc | quote }}
  {{- end }}
{{- end }}
